
SELECT
t.CODPRO AS "COD_PRODUTO",
'' AS COD_GRADE,
t.DESCPRO AS "DESC_PRODUTO",
t.CST AS "COD_IMPOSTO",
'' AS "DESC_IMPOSTO",
'' AS "REFERENCIA",
t.CODBARUN AS "COD_BARRA",
'' AS "COD_BALANCA",
t.PESOLIQUIDO AS "PESO_LIQUIDO",
t.PESOBRUTO  AS "PESO_BRUTO",
t.UNIDADE AS "UNIDADE",
tf.PRVAPRO AS "VR_PRAZO",
'' AS "VR_VISTA",
tf.PRCUPRO AS "VR_CUSTO",
'' AS "OBS",
t.CLASFISCAL AS "NCM",
'' AS "FLAG_ATIVO",
t.GRUPRO AS "COD_GRUPO",
tg.NOMGRU AS "DESC_GRUPO",
t.CEST AS "CEST"
FROM TABPRO t
LEFT JOIN TABPROFIL tf
ON tf.CODPRO = t.CODPRO
LEFT JOIN TABGRU tg
ON tg.CODGRU = t.GRUPRO